// src/components/Map/regionMap.ts

export const cityToRegion: Record<string, string> = {
  // Marmara
  Balıkesir: "Marmara",
  Bilecik: "Marmara",
  Bursa: "Marmara",
  Çanakkale: "Marmara",
  Edirne: "Marmara",
  İstanbul: "Marmara",
  Kirklareli: "Marmara",
  Kırklareli: "Marmara",
  Kocaeli: "Marmara",
  Sakarya: "Marmara",
  Tekirdağ: "Marmara",
  Yalova: "Marmara",

  // Aegean
  Afyon: "Aegean",
  Afyonkarahisar: "Aegean",
  Aydın: "Aegean",
  Denizli: "Aegean",
  İzmir: "Aegean",
  Izmir: "Aegean",
  Kütahya: "Aegean",
  Kutahya: "Aegean",
  Manisa: "Aegean",
  Muğla: "Aegean",
  Mugla: "Aegean",
  Uşak: "Aegean",
  Usak: "Aegean",

  // Mediterranean
  Adana: "Mediterranean",
  Antalya: "Mediterranean",
  Burdur: "Mediterranean",
  Hatay: "Mediterranean",
  Isparta: "Mediterranean",
  Kahramanmaraş: "Mediterranean",
  Kahramanmaras: "Mediterranean",
  Mersin: "Mediterranean",
  Osmaniye: "Mediterranean",

  // Central Anatolia
  Aksaray: "Central Anatolia",
  Ankara: "Central Anatolia",
  Çankırı: "Central Anatolia",
  Cankiri: "Central Anatolia",
  Eskişehir: "Central Anatolia",
  Eskisehir: "Central Anatolia",
  Karaman: "Central Anatolia",
  Kayseri: "Central Anatolia",
  Kırıkkale: "Central Anatolia",
  Kirikkale: "Central Anatolia",
  Kırşehir: "Central Anatolia",
  Kirsehir: "Central Anatolia",
  Konya: "Central Anatolia",
  Nevşehir: "Central Anatolia",
  Nevsehir: "Central Anatolia",
  Niğde: "Central Anatolia",
  Nigde: "Central Anatolia",
  Sivas: "Central Anatolia",
  Yozgat: "Central Anatolia",

  // Black Sea
  Amasya: "Black Sea",
  Artvin: "Black Sea",
  Bartın: "Black Sea",
  Bartin: "Black Sea",
  Bayburt: "Black Sea",
  Bolu: "Black Sea",
  Çorum: "Black Sea",
  Corum: "Black Sea",
  Düzce: "Black Sea",
  Duzce: "Black Sea",
  Giresun: "Black Sea",
  Gümüşhane: "Black Sea",
  Gumushane: "Black Sea",
  Karabük: "Black Sea",
  Karabuk: "Black Sea",
  Kastamonu: "Black Sea",
  Ordu: "Black Sea",
  Rize: "Black Sea",
  Samsun: "Black Sea",
  Sinop: "Black Sea",
  Tokat: "Black Sea",
  Trabzon: "Black Sea",
  Zonguldak: "Black Sea",

  // Eastern Anatolia
  Ağrı: "Eastern Anatolia",
  Agri: "Eastern Anatolia",
  Ardahan: "Eastern Anatolia",
  Bingöl: "Eastern Anatolia",
  Bingol: "Eastern Anatolia",
  Bitlis: "Eastern Anatolia",
  Elazığ: "Eastern Anatolia",
  Elazig: "Eastern Anatolia",
  Erzincan: "Eastern Anatolia",
  Erzurum: "Eastern Anatolia",
  Hakkâri: "Eastern Anatolia",
  Hakkari: "Eastern Anatolia",
  Iğdır: "Eastern Anatolia",
  Igdir: "Eastern Anatolia",
  Kars: "Eastern Anatolia",
  Malatya: "Eastern Anatolia",
  Muş: "Eastern Anatolia",
  Mus: "Eastern Anatolia",
  Tunceli: "Eastern Anatolia",
  Van: "Eastern Anatolia",

  // Southeastern Anatolia
  Adıyaman: "Southeastern Anatolia",
  Adiyaman: "Southeastern Anatolia",
  Batman: "Southeastern Anatolia",
  Diyarbakır: "Southeastern Anatolia",
  Diyarbakir: "Southeastern Anatolia",
  Gaziantep: "Southeastern Anatolia",
  Kilis: "Southeastern Anatolia",
  Mardin: "Southeastern Anatolia",
  Siirt: "Southeastern Anatolia",
  Şanlıurfa: "Southeastern Anatolia",
  Sanliurfa: "Southeastern Anatolia",
  Şırnak: "Southeastern Anatolia",
  Sirnak: "Southeastern Anatolia",
};